### ISSUE TITLE
DEMO Issues

### ISSUE THREAD

**Issue by AJVelezRueda** [BioinformaticaUNQ/Interacpy#2]
Durante la demo pudimos observar los siguientes errores:

**MAYOR PRIORIDAD**
- [x] **Los test rompen, deben correr bien**
![Screenshot from 2024-12-18 18-33-50](https://github.com/user-attachments/assets/53645c92-aed4-4341-b356-86fcac9e2b1f)
- [x] #3
- [x] **El mapeo de PDB a uniprot no muestra el uniprot ID si no el gen name**
![Screenshot from 2024-12-18 18-22-02](https://github.com/user-attachments/assets/c18a2cbd-8393-443d-a513-e611a3b20be3)
![Screenshot from 2024-12-18 18-22-37](https://github.com/user-attachments/assets/3fe4beb8-104a-48d3-9713-cf15636ff65d)
![Screenshot from 2024-12-18 18-22-54](https://github.com/user-attachments/assets/d772adfe-78d6-4e0d-8102-ced9e306f9d9)
este mapeo deberia arreglarse para que muestre en cada nodo del grafo el ID de la proteina exacta que interactúa con la protaína problema
- [x] Cuando se llama el programa con el uniprot, la salida en el grafo no dice el nombre de la proteina problema
![Screenshot from 2024-12-18 18-31-55](https://github.com/user-attachments/assets/8d8f7863-d7b6-4e98-994d-c523cbc550d8)

- [x] El ensemble ID debería ser ENS(numero), yo tengo que poder buscarlo en el buscador de Enseble y que me lo ecuentre y que me sirva para hacer crosslink automatico con otras bases
- [x] El manejo de errores deberia mejorar, por ejemplo cuando se introduce un uniprot invalido el error que arroja es incorrecto, dice "no se puede descargar la secuencia" deberia decirte que es invalido el codigo (fijate  tal vez usar el error que tira la API)
![Screenshot from 2024-12-18 18-47-59](https://github.com/user-attachments/assets/2f9539a5-d8ae-45a5-953d-33f964b8808b)

**SERÍA DESEABLE**
- [x] No soporta la salidas múltiples (solo se guarda un tipo de mapeo a la vez), y que se guarden todos los archivos de forma individual cada tipo de mapeo (los json y los grafos)

**Comment by GoorgeEsp** [comment]
El grafo de visualización de interacciones no se persiste a disco: agregar esa feature, el usuario debe poder acceder en cualquier momento despues de corrida una vez, si tenemos que correr varias veces el programa es ineficiente

<img width="433" alt="image" src="https://github.com/user-attachments/assets/2b0ab693-a75b-431f-99d4-a8611f3653c6" />

<img width="152" alt="image" src="https://github.com/user-attachments/assets/e07c4292-7b18-407e-bc8e-5c090ad7d486" />

**Comment by GoorgeEsp** [comment]
El ensemble ID debería ser ENS(numero), yo tengo que poder buscarlo en el buscador de Enseble y que me lo ecuentre y que me sirva para hacer crosslink automatico con otras bases
 
 <img width="667" alt="image" src="https://github.com/user-attachments/assets/123a5348-1e19-40e0-ae07-77dca827f54c" />

**Comment by GoorgeEsp** [comment]
El manejo de errores deberia mejorar, por ejemplo cuando se introduce un uniprot invalido el error que arroja es incorrecto, dice "no se puede descargar la secuencia" deberia decirte que es invalido el codigo (fijate tal vez usar el error que tira la API)

<img width="610" alt="image" src="https://github.com/user-attachments/assets/f6d25300-7608-4501-bf56-b7c000e4e7c4" />

<img width="551" alt="image" src="https://github.com/user-attachments/assets/ea087a8d-2e12-44a2-adaa-e283cfef8232" />

**Comment by GoorgeEsp** [comment]
El mapeo de PDB a uniprot no muestra el uniprot ID si no el gen name
 
 <img width="678" alt="image" src="https://github.com/user-attachments/assets/27c0bf18-4895-4f05-bb26-70e09ce0e51a" />

**Comment by GoorgeEsp** [comment]
Los test rompen, deben correr bien

<img width="661" alt="image" src="https://github.com/user-attachments/assets/671846a7-47d0-45ad-ba40-4a0b0b5e406c" />

**Comment by GoorgeEsp** [comment]
No soporta la salidas múltiples (solo se guarda un tipo de mapeo a la vez), y que se guarden todos los archivos de forma individual cada tipo de mapeo (los json y los grafos)

<img width="143" alt="image" src="https://github.com/user-attachments/assets/340aba04-07d3-41af-adbf-a88d83a2f28e" />

<img width="977" alt="image" src="https://github.com/user-attachments/assets/d06c25ec-0b8d-4518-b855-5f98890197d0" />

<img width="404" alt="image" src="https://github.com/user-attachments/assets/238e28e1-1e20-4aca-b0fc-70c43c46d3a3" />

<img width="413" alt="image" src="https://github.com/user-attachments/assets/a672dc6d-3098-41c5-a4bf-40b8d3f0da7c" />
